import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Featured from '../components/Featured'
import Pizza from '../components/Pizza'
import styles from '../styles/Home.module.scss'

export default function Home({pizzalist}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kanairo Cafe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
       <Featured />
       <Pizza pizzalist={pizzalist}/>
    </>
    
    </div>
   
 
  )
}


export const getServerSideProps = async () => {
  const res = await axios.get('http://localhost:3000/api/products')
  return{
    props: {
      pizzalist: res.data,
    }
  }
}